version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4-node
      - image: circleci/postgres:9.4.12-alpine
        environment:
          POSTGRES_USER: circleci-demo-ruby
          POSTGRES_DB: people_of_peace_development
          POSTGRES_PASSWORD: ""
    working_directory: ~/circleci-demo-workflows
    steps:
      - checkout
      - run: bundle install --path vendor/bundle  # install dependencies
      - run: bundle exec rake db:create db:schema:load  # setup database
      - run:
          name: Run tests
          command: rake

  deploy:
    machine:
        enabled: true
    working_directory: ~/circleci-demo-workflows
    environment:
      HEROKU_APP: "glacial-brook-53259"
    steps:
      - checkout
      - add_ssh_keys:  # add key from CircleCI account based on fingerprint
                fingerprints:
                  - "SHA256:iUKnX3Yze4VqnzUP9H8rHZjJx7zY5WAJxlAsmPO9ncU pbrudny@macbook-pro-pbrudny.home"
      - run:
          name: Setup Heroku
          command: bash .circleci/setup-heroku.sh

      - run:
          command: |
            git push heroku sequential-branch-filter:master
            heroku run rake db:migrate
            sleep 5  # sleep for 5 seconds to wait for dynos
            heroku restart

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: sequential-branch-filter
